name: After PR Create
# on:
#   pull_request:
#     types: [opened]
on: push

jobs:
  print-pr-create:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Create
        run: echo "pull request is created."
  test-job:
    # 버전별 테스트 방법
    strategy:
      matrix:
        node-version: [12, 18] # node-version은 사용자가 임의로 설정해준 이름, ubuntu-latest에서는 20버전이 기본적으로 설치되어 있음, 그래서 20버전 외의 버전을 사용하려면 추가적으로 명시해줘야 함
    runs-on: ubuntu-latest
    needs: print-pr-create
    steps:
      # 1. 내 github repo 코드를 github cloud server로 전송
      - name: Get Codes
        uses: actions/checkout@v4

      # 특정 버전의 노드를 yml 파일을 통해서 설치할 수 있다.
      # - actinos/setup-node@v4: https://github.com/actions/setup-node
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 2. 의존성 파일들 설치
      - name: Install Dependencies
        run: npm install

      # 3. 테스트 실행
      - name: Run Test
        run: npm run test
  build-job:
    runs-on: ubuntu-latest
    # test-job이 성공적으로 끝나야만 build-job이 실행될 수 있도록 설정
    needs: test-job
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run build
        run: npm run build
